### ISSUE TITLE
Do not dismiss notification after auto reply

### ISSUE THREAD

**Issue by OLLI-S** [adeekshith/watomatic#189]
When Watomatic replies to a message, it is shown as "Read" in WhatsApp.
Would be very useful, when the message stays "Unread" or "New", so I know that there is a new message where Watomatic replied to.
This way I can check the message and see if I missed something.

**Comment by adeekshith** [comment]
Working on a feature where the notification will not be dismissed even after auto reply (Android 8+)

**Comment by OLLI-S** [comment]
Cool, thank you!

**Comment by OLLI-S** [comment]
When will this be released (Google Play Store)?
(I have turned Watomatic currently off, because I missed some important messages but will turn it on as soon as this feature is released).

**Comment by adeekshith** [comment]
Hi @OLLI-S 👋
Plan was to release tomorrow. Will try to make it but otherwise by Monday. And it usually takes about 2 to 3 days days for Google Play to approve so you should get this update sometime next week.

> I have turned Watomatic currently off, because I missed some important messages but will turn it on as soon as this feature is released

Yeah this feature took some time to implement. It still has a few issues like the notification icon is tiny and other minor issues. So I am planning to release it but keeping it OFF by default.
You can go to settings and enable it once released. Thanks for your patience 😊

**Comment by OLLI-S** [comment]
Today I received the update.
I activated Watomatic and asked my wife to send me a WhatsApp message.
I received it and she received the auto reply.

But the WhatsApp icon on the home screen does not show me a number (new message).
When I open WhatsApp, then there is in the list of contacts also no counter behind my wife.
So, what is wrong?

**Comment by adeekshith** [comment]
Watomatic notifications are not enabled by default for existing users to preserve behavior.

Enable it by: Open Watomatic -> Click on top right three dots -> Settings -> Toggle "Show notification for replied messages"

This generates new Watomatic notifications for replied messages... clicking on which will open WhatsApp.

But note that WhatsApp might still not show those messages as unread because WhatsApp thinks user has replied to those messages.

Try this out and let me know if it is working for you. 

![1619456004266.png](https://user-images.githubusercontent.com/2568945/116122149-059e7a80-a687-11eb-989b-9b21d811d4cb.png)

**Comment by OLLI-S** [comment]
Thank you for the information, the feature is working very well.
But why have you "hidden" it in the settings?
It would be more user friendly to show it on the main screen directly below the switch "Auto Reply ON".

**Comment by OLLI-S** [comment]
@adeekshith 
I added my Google Play rating for your app (5 stars).
And please read my comment above.

**Comment by adeekshith** [comment]
Hi @OLLI-S 👋😃
Thanks a lot!

> But why have you "hidden" it in the settings?
It would be more user friendly to show it on the main screen directly below the switch "Auto Reply ON".

Sorry I saw your message when you posted. Wanted to give a bit detailed reply but then procrastinated and missed it 🙈.

Few reasons why it is hidden in the settings:
- Support small screens
  On smaller screens, the options get overflowed and users cannot view them until they scroll. More importantly, not everyone scrolls a UI intuitively. For example, I received an email saying they do not see "Reply Frequency" option in the app and I had to ask them to scroll 😄. Attaching a small screen screenshot below.
<img width="150" alt="wato-tiny-screen" src="https://user-images.githubusercontent.com/2568945/117009279-2da66300-acb1-11eb-85e7-591f38bfc987.png">

- Set sane defaults instead of showing all options
  Too many options can confuse average users ([Hick's law](https://lawsofux.com/hicks-law/)). Notifications is a feature most would like to have it enabled. So enabled this by default for all new installs. But had to keep it disabled for existing users to prevent changing existing behavior without their permission.

So the idea is to keep frequently changing options on the main page and rarely changing options like language, etc hidden in settings.

But a few things I did not do right or did not do it yet:
- Educating existing users about the all the new features using tooltip popups would have been great but could not get to implement it yet:
<img width="150" alt="wato-tiny-screen" src="https://user-images.githubusercontent.com/2568945/117012668-cee2e880-acb4-11eb-9fbd-203bce0e40e1.jpeg">
- Settings button should probably be more visible if we are not training the users with UI popups like above.


----
That said, I am not at all defending that this is the best UI. I should take a break from implementing new features and focus more on polishing UI/UX sometime. Should also learn more and ask for contributions/advice from people who know more about UI/UX than me.

**Comment by OLLI-S** [comment]
> So enabled this by default for all new installs. But had to keep it disabled for existing users to prevent changing existing behavior without their permission.

This is right, changing a setting after wards that changes the behaviour is confusing users.
You are totally right!

> Educating existing users about the all the new features using tooltip popups

This would be a good way to inform users about new features...

> That said, I am not at all defending that this is the best UI. I should take a break from implementing new features and focus more on polishing UI/UX sometime. Should also learn more and ask for contributions/advice from people who know more about UI/UX than me.

You do a fantastic job, continue implementing new features.
You have only some usability issues that needs an urgent fix.

I suggest that you move all options on the main window and **add scrollbars**.
Scrollbars indicate that there is more content below.
This is IMHO the best option!
