### ISSUE TITLE
Add support for Linux 

### ISSUE THREAD

**Issue by iMonZ** [adeekshith/watomatic#279]
Is it possible to add Linux cli support?
It would be a nice feature to put this application on my RaspberryPi.

**Comment by mawoka-myblock** [comment]
It won't be possible, because Watomatic uses the notification-api from android. You could set up an android-vm on your raspberry pi and install it there.

**Comment by mawoka-myblock** [comment]
Here is a tutorial how to set up an android-vm: https://docs.mau.fi/bridges/go/whatsapp/android-vm-setup.html

**Comment by iMonZ** [comment]
Maybe there is a possible way with xamarin?

> It won't be possible, because Watomatic uses the notification-api from android. You could set up an android-vm on your raspberry pi and install it there.

**Comment by iMonZ** [comment]
> Here is a tutorial how to set up an android-vm with WhatsApp: https://docs.mau.fi/bridges/go/whatsapp/android-vm-setup.html

All right I’m gonna try that thanks

**Comment by mawoka-myblock** [comment]
> Maybe there is a possible way with xamarin?
> 
> > It won't be possible, because Watomatic uses the notification-api from android. You could set up an android-vm on your raspberry pi and install it there.

It won't be possible, because Watomatic looks for notifications on your device. Theny if a notification comes from WhatsApp, it taps the `reply` button and pasts the text you set up in  Watomatic. (Not really like this but you can imagine like this). So Watomatic doesn't communicate with WhatsApp directly, it communicates with the WhatsApp notifications over an Android-notification-api.
