### ISSUE TITLE
List Watomatic on F-Droid - lizzyOnDroid repo and possibly on main repo

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#65]
~### Implement Play store in app review~

~Come up with a logic to determine user has sufficiently used the app and then ask for review using in-app review: https://developer.android.com/guide/playcore/in-app-review/~
~Suggestions for triggering:~
~- 5 days of usage~
~- 10 auto reply messages sent~

**Comment by IzzySoft** [comment]
Be aware that this library is non-free (just free as in "free beer", but proprietary and thus not "libre"), so your app would no longer be fully F/LOSS if you integrate it.

Besides: did you consider attaching a ***signed*** APK to releases? The one currently attached is unsigned and thus cannot be directly installed. Catch two flies at once, helping people to also leave the walled garden of Google by making a directly usable APK available :smiley:

**Comment by adeekshith** [comment]
> Be aware that this library is non-free

Glad you mentioned. I should've realized that 🤦‍♂️. Ok then, will fallback to the good old ways of sending people to play store/alternative to give a rating.

> Did you consider attaching a signed APK to releases? The one currently attached is unsigned and thus cannot be directly installed.

Hmm I was signing it. Now I am confused. Let me try installing on an spare phone and see. But that said, the signature of the app on Google play is not the same as on Github. Google tricked me into signing with its own key and there is no way to revert that. Well it is convenient but the app cannot be updated outside play store without uninstalling the play store version. Probably thats what happened in your case?

> Catch two flies at once, helping people to also leave the walled garden of Google by making a directly usable APK available

Agree! thats the way to go! 😃 Was thinking of getting this published on [F-Droid](https://f-droid.org/). No idea how to but will figure that out.

**Comment by adeekshith** [comment]
@IzzySoft Wait! You are Izzy as in IzzyOnDroid F-Droid Repository right? Sorry did'nt realize that. Glad to have you taking a look at this! It is an honor!
Yeah would love to get this published either on IzzyOnDroid or the main F-Droid repos!

**Comment by IzzySoft** [comment]
> will fallback to the good old ways of sending people to play store/alternative to give a rating.

Guess that's the safest way (those Google libs are pretty sneaky: even if they themselves are presented with a FOSS license, earlier or later they drag in some nasty proprietary stuff. We've had that too often). Along those lines: when implementing this, consider planning it with a flavor. Looks strange if an app installed from F-Droid asks for a Play Store rating :wink:

> I was signing it.

"All the way down" – or just some "higher version"? If you eg sign with v3, make sure you also tick the boxes to include v2 and v1. Often it's a forgotten v1 signature for an app with minSdk set to before Nougat (which requires v1) causing those "unsigned" errors. I've tested with `apksigner verify --verbose *.apk`.

> Google tricked me into signing with its own key and there is no way to revert that.

Another of Google's ugly tricks. While you cannot revert it, you could use a different packageName to list it as "new app". Though that would just be postponing things: you could get that app in now, but you couldn't update it anymore after 11/2021 without falling for the same trap. I've heard of several devs considering to drop their apps out of Play then. And honestly, it's a bad idea to hand out your private keys. Whoever has them can modify your app in any way they want, in your name, and users would blame – you. But I guess I'm preaching the choir here as you already figured.

> Well it is convenient but the app cannot be updated outside play store without uninstalling the play store version. Probably thats what happened in your case?

That's almost always the case if you try to switch from Play to F-Droid – but no, that's not what happened to me. I've never used WA, and do not plan to (you know why). I've just checked with `apksigner`, because…

> Wait! You are Izzy as in IzzyOnDroid F-Droid Repository right?

Yupp – and I was looking to add your app to my repo, so this was the pre-check :smile: While I usually do not even *consider* adding any WA-Addons, your app is something much different – helping people to get out of risky waters. Which very much meets my own goals.

> Yeah would love to get this published either on IzzyOnDroid or the main F-Droid repos!

Glad to read, thanks! We can start with my repo first (as a pre-stage) and then file an RFP (Request for Packaging) with F-Droid (disclaimer: I'm one of the maintainers there, too). Once your app shows up there, I'd remove it from my repo again (enough that there are 2 different signatures to fiddle with, we don't need a third I guess). Or if you prefer we can skip mine and you go straight for the "official repo" – apart from the missing signature (which does not affect F-Droid at all as apps there are built from source and signed with keys generated at F-Droid), all looks pretty well – e.g. my library scanner showed no culprits.

Just let me know which approach you prefer. For my repo I'd need a properly signed APK (but then could have your app listed in less than 24h) – for F-Droid we don't need the APK, but getting the app listed will take at least a week or two.

**Comment by adeekshith** [comment]
> when implementing this, consider planning it with a flavor. Looks strange if an app installed from F-Droid asks for a Play Store rating

Of course. Totally makes sense. Will do that.

> Often it's a forgotten v1 signature for an app with minSdk set to before Nougat

Ah! Thats what I missed. Updated latest release with both v1 and v2 signatures checked. Thanks for helping with this! `apksigner verify` error is gone now

> you couldn't update it anymore after 11/2021 without falling for the same trap. I've heard of several devs considering to drop their apps out of Play then

That is sad but would be a great push for F-Droid community I hope.

> it's a bad idea to hand out your private keys. Whoever has them can modify your app in any way they want, in your name, and users would blame

yep 😕

> While I usually do not even consider adding any WA-Addons, your app is something much different – helping people to get out of risky waters. Which very much meets my own goals.

Very glad to hear that 😀

> Glad to read, thanks! We can start with my repo first (as a pre-stage) and then file an RFP (Request for Packaging) with F-Droid

Awesome! That would be really great! Yep, lets go with your repo first and then work on getting on main F-Droid 😃
Anything you want me to do from my end to get this on your repo?

**Comment by IzzySoft** [comment]
I can confirm the signature issue being solved, thanks! So your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.parishod.watomatic) with the next sync (around 7:45 pm CET/UTC+1 tomorrow). Once you think you're ready for the "official repo", you can simply open an [RFP](https://gitlab.com/fdroid/rfp/issues) yourself. We'll meet there again when it gets processed. To make the process easier for you, I've already prepared Fastlane metadata (see #81) for your app. I'd suggest you wait applying until the next release has been tagged, as Fastlane must be available at the latest tag.

Thanks a lot!

**Comment by adeekshith** [comment]
Yayy! Excited to see this on your repo and will follow your instructions for F-Droid submission. Thank you for patiently explaining the process and taking time to make PR #81 for fastlane. I really appreciate it!

**Comment by IzzySoft** [comment]
Gladly! Are you prepared for some publicity? Run will start shortly. I've just been contacted by one of our most famous security experts here in Germany, sounds like he's having a look now and will "introduce" it shortly – which usually means a lot of users will show up soon :smile:

PS: [here's a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) you can use to point out availability in my repo if you want. Countdown running, 4.5h and counting down :smiley:

**Comment by adeekshith** [comment]
Woww! What more can I ask.. I am very excited! 🙌😃

Sure, will point to your repo in a little while

Yayy 😀

I made a release just a while ago [1.7](https://github.com/adeekshith/watomatic/releases/tag/v1.7) with some new features and also removed play store specific URLs to make it not look like a second class citizen on F-Droid repos.

**Comment by IzzySoft** [comment]
> I am very excited!

So am I! Mike just had a [post on this problem today](https://social.tchncs.de/@kuketzblog/105756515586378361), calling people to finally leave WA. So I responded to him I'd knew something helpful, naming your app. He responded immediately asking for details, which I provided. So he obviously already had a look at your repo and your app, [because of](https://social.tchncs.de/@kuketzblog/105758579454682159). This now went out to his almost 6k followers, plus my over 1k followers, and several of them (those "on the leave") are eagerly awaiting "the event" (your app showing up in my repo) – I already receive quite some boosts and stars [on Mastodon](https://mastodon.technology/@IzzyOnDroid/105757848116874404) :smiley:

> Sure, will point to your repo in a little while

Great, thanks!

> I made a release just a while ago

Right in time! That will be picked up before the sync and show up in my repo in about 2.5h from now. Thanks a lot! If you're not opposed, I could try triggering some other well-known sources here. I'm pretty sure at least one of them will pick it up pretty soon. The other one is outside the "privacy bubble" and a "big egg" that doesn't move that fast – but when it does, it will be a pretty big wave… Though, it's all just the German speaking community.

**Comment by adeekshith** [comment]
> I already receive quite some boosts and stars on Mastodon

👏😃 This is a really great response I was not expecting. Also great to see Mastodon rising. Will join you there

> I could try triggering some other well-known sources here

Of course, feel free to. That would be really great! Thank you so much Izzy!

**Comment by IzzySoft** [comment]
Gladly, again! Feel the beat already? Countdown is down to around 20min now, your update has already been fetched. Watch the stars which hopefully will rise! As soon as it's online, I'll ping the last source on my list.

And yeah – see you at our ice-age farm, among the friendly Mastodons :smiley:

**Comment by IzzySoft** [comment]
It's live now! Unfortunately it seems the [traffic graph](https://github.com/adeekshith/watomatic/graphs/traffic) isn't public, I'd really be curious :smile:

Thanks for adding the badge!

**Comment by adeekshith** [comment]
Yayy! I see the listing is up 🥳. Added IzzyOnDroid badges on [Readme](https://github.com/adeekshith/watomatic) as well as the [webpage](https://git.io/watomatic).

**Comment by adeekshith** [comment]
>  traffic graph isn't public, I'd really be curious

Oh did'nt realize that. Sorry could not find a quick setting. Will get back to in a few hours after my day job.
Until then here is a screenshot which I took just now if it helps 😊

![wat-stats](https://user-images.githubusercontent.com/2568945/108550901-cd5c7380-72b4-11eb-9953-56ae345c1c14.png)

**Comment by IzzySoft** [comment]
> Oh did'nt realize that. Sorry could not find a quick setting.

Neither did I, and neither did I. If you find a setting exposing that, please let me know. But my guess is it is not intended to be public but restricted to members of the project. What I was curious for was mostly the second graph; I'd expected a peak with visitors, as I posted a link to your repo here before your app went online in mine. Now it will become interesting what happens in my repo…

**Comment by adeekshith** [comment]
Yeah, looks like only collaborators can view traffic stats. Invited you as collaborator.

> Now it will become interesting what happens in my repo

Me too. I could not find but by any chance, does your repo has any public stats to see how many times a specific app page was visited or downloaded?

**Comment by IzzySoft** [comment]
Thanks, that worked – I can see them now!

And no, my repo has no stats. And the cumulated web stats (done by log parsing) won't show much – for that this action should have been on the beginning of the month. But as far as I can see by checking the logs with GoAccess, there were already 840 requests before the app went online (getting a 404). 116 downloads so far (so about 25 per hour).

**Comment by adeekshith** [comment]
That is awesome 😃

**Comment by IzzySoft** [comment]
First article appeared today in Switzerland: [Watomatic - automatische Antworten auf WhatsApp-Nachrichten](https://gnulinux.ch/watomatic-automatische-antworten-auf-whatsapp-nachrichten). I'm still waiting for responses concerning my articles…

**Comment by adeekshith** [comment]
Woohoo! Thats a nice one. Thanks a lot for your involvement Izzy!
We have been working on FB integration and other bug fixes so deploying to F-Droid took a little backseat. Actually, I think you already did most of the base work to get this on F-droid. I will do the rest including updating the screenshots so it can be on F-droid main repo soon 😃

**Comment by adeekshith** [comment]
Was thinking, if this app can be posted to any of these popular subreddits like [r/privacy](https://www.reddit.com/r/privacy/) or [r/privacytoolsIO](https://www.reddit.com/r/privacytoolsIO/), that would give it a real boost. I cannot post it myself as it will be considered as self promotion/spam. Tried to get in touch with the moderators but got no response. In those subs, they discuss about WhatsApp and Facebook related privacy issues every other day and it is unfortunate we could not reach them yet.

**Comment by IzzySoft** [comment]
Would certainly fit. But I cannot do it either as I do not even have a Reddit account (and neither plan to create one, before you ask :laughing:).

Btw: first answer on my article came in, they're considering it (just discussing in the team there now). I'll keep you updated. You might consider a wiki page here, like "Watomatic in the press", to collect the links in :wink:

**Comment by adeekshith** [comment]
> I do not even have a Reddit account (and neither plan to create one, before you ask 😆)

😂 I think I almost knew that

> first answer on my article came in, they're considering it 

Thats awesome! Thank you very much! 🙌


Created wiki page too 😁
https://github.com/adeekshith/watomatic/wiki/Watomatic-in-the-press

**Comment by IzzySoft** [comment]
Nice! Added that link as "website" to your app's details. And couldn't resist tooting that screenshot :rofl:

**Comment by adeekshith** [comment]
I signed up on https://mastodon.technology instance and it is under review. Will see you there shortly 😃

**Comment by IzzySoft** [comment]
Ah! That's the instance I'm on. Ash (the one running it) is fantastic, as I found out after having been there for a while. Instance is well maintained, in good hands. Good choice! Find me there as IzzyOnDroid, and also fdroidorg (the official F-Droid account) is on that instance. Looking forward to see you there then!
